config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  pid_format_constraint = %r{[^/]+(?:/[^/]+)?}

  ############################## IMPORTANT!!! ################################
  # !!! Code of high security risk impact !!!
  # AAI service authentication is skipped for tests purpose
  get "users/login" => "users/auth_mock#login" if Rails.env.development? && Mp::Application.config.auth_mock

  #############################################################################

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: [:sessions]
  as :user do
    delete "users/logout", to: "devise/sessions#destroy", as: :destroy_user_session
  end

  get "health_check", to: "rails/health#show", as: :rails_health_check
  get "service_autocomplete", to: "services#autocomplete", as: :service_autocomplete
  get "/robots.txt" => "home#robots"
  post "user_action", to: "user_action#create"
  if ActiveModel::Type::Boolean.new.cast(ENV.fetch("MP_ENABLE_EXTERNAL_SEARCH", false))
    get "/", to: "pages#landing_page", as: :new_landing_page
  end
  get "/datasources/:id", to: redirect("/services/%{id}")
  get "backoffice/datasources/:id", to: redirect("backoffice/services/%{id}")

  scope "/services" do
    get "/c/:category_id", to: "services#index", as: :category_services
  end
  resources :services, only: %i[index show], constraints: { id: pid_format_constraint } do
    scope module: :services do
      resources :offers, only: %i[index] do
        scope module: :offers do
          resources :notifications, only: %i[create destroy]
        end
      end
      resource :choose_offer, only: %i[show update]
      resource :configuration, only: %i[show update]
      resource :information, only: %i[show update]
      resource :summary, only: %i[show create]
      resource :cancel, only: :destroy
      resource :logo, only: :show
      resource :question, only: %i[new create]
      resources :opinions, only: :index
      resources :details, only: :index
      resources :guidelines, only: :index
      resources :bundles, only: :show
      resource :ordering_configuration, only: :show do
        scope module: :ordering_configuration do
          resources :offers, only: %i[index new edit create update destroy] do
            resource :publish, controller: "offers/publishes", only: :create
            resource :draft, controller: "offers/drafts", only: :create
            resource :summary, controller: "offers/summaries", only: %i[create update]
          end
          resources :bundles, only: %i[index new edit create update destroy] do
            resource :publish, controller: "bundles/publishes", only: :create
            resource :draft, controller: "bundles/drafts", only: :create
          end
        end
      end
    end
  end

  resource :comparisons, only: %i[show destroy] do
    scope module: :comparisons do
      resource :services, only: %i[create destroy]
    end
  end

  resources :categories, only: :show

  resources :catalogues, only: %i[index show] do
    scope module: :catalogues do
      resource :logo, only: :show
    end
  end

  resource :reports, only: %i[new create], constraints: lambda { |req| req.format == :js }

  resources :projects do
    scope module: :projects do
      resource :add, only: :create
      resource :archive, only: :create
      resources :about, only: :index
      resources :research_products, only: %i[show index destroy]
      resources :services, only: %i[show index] do
        scope module: :services do
          resource :opinion, only: %i[new create]
          resource :conversation, only: %i[show create]
          resource :timeline, only: :show
        end
      end
      resource :conversation, only: %i[show create]
    end
  end

  resource :profile, only: %i[show edit update destroy]

  resources :providers, only: %i[index show], constraints: { id: pid_format_constraint } do
    scope module: :providers do
      resource :question, only: %i[new create]
      resources :details, only: :index
      resource :logo, only: :show
    end
  end

  resources :research_products, only: %i[new create]

  resources :favourites, only: :index
  post "favourites/services", to: "favourites/services#update"

  resource :help, only: :show, path: "user_documentation"

  resource :backoffice, only: :show
  namespace :backoffice do
    scope "/services" do
      get "/c/:category_id", to: "services#index", as: :category_services
    end
    namespace :statuses do
      resources :services, only: %i[create]
      resources :providers, only: %i[create]
      resources :catalogues, only: %i[create]
    end
    resources :services, controller: "services", constraints: { id: pid_format_constraint } do
      scope module: :services do
        resource :logo_preview, only: :show
        resources :offers do
          resource :publish, controller: "offers/publishes", only: :create
          resource :draft, controller: "offers/drafts", only: :create
          resource :summary, controller: "offers/summaries", only: %i[create update]
          post :exit
        end
        resources :bundles do
          resource :publish, controller: "bundles/publishes", only: :create
          resource :draft, controller: "bundles/drafts", only: :create
        end
        resource :publish, only: :create
        resource :draft, only: :create
      end
    end
    get "service_autocomplete", to: "services#autocomplete", as: :service_autocomplete
    resources :approval_requests, only: %i[index show edit update]
    resources :providers, constraints: { id: pid_format_constraint } do
      resource :publish, controller: "providers/publishes", only: :create
      resource :unpublish, controller: "providers/unpublishes", only: :create
      resource :wizard, controller: "providers/steps", only: %i[show update]
      post :exit
    end
    resources :catalogues do
      resource :publish, controller: "catalogues/publishes", only: :create
      resource :unpublish, controller: "catalogues/unpublishes", only: :create
    end
    resources :statistics, only: :index
    get "other_settings", to: "other_settings/scientific_domains#index", as: :scientific_domains
    namespace :other_settings do
      resources :scientific_domains
      resources :categories
      resources :platforms
      get "vocabularies", to: "vocabularies#index", type: "target_user", as: :vocabularies
      scope "/vocabularies" do
        VOCABULARY_TYPES.each do |type, opts|
          resources opts[:route], controller: "vocabularies", type: type.to_s
        end
      end
    end
  end

  post "/backoffice/services/:service_id/offers/:offer_id/duplicate", to: "backoffice/services/offers#duplicate",
    as: :duplicate_offer

  post "/backoffice/services/:service_id/offers/fetch_subtypes", to: "backoffice/services/offers#fetch_subtypes"

  resource :executive, only: :show
  namespace :executive do
    resources :statistics, only: :index
  end

  mount Rswag::Ui::Engine => "/api_docs/swagger"
  mount Rswag::Api::Engine => "/api_docs/swagger"

  namespace :api do
    get "/services" => "services#index", :defaults => { format: :json }, :as => :services_api
    namespace :webhooks do
      post "/jira" => "jiras#create", :as => :jira
    end

    namespace :v1 do
      resources :resources, only: %i[index show], constraints: { id: pid_format_constraint } do
        resources :offers, only: %i[index create show destroy update], module: :resources
      end
      resources :oms, controller: :omses, only: %i[index show update] do
        resources :events, only: :index, module: :omses
        resources :messages, only: %i[index show create update], module: :omses
        resources :projects, only: %i[index show update], module: :omses do
          resources :project_items, only: %i[index show update], module: :projects
        end
      end
      namespace :ess do
        resources :services, only: %i[index show], constraints: { id: pid_format_constraint }
        resources :datasources, only: %i[index show], constraints: { id: pid_format_constraint }
        resources :providers, only: %i[index show]
        resources :catalogues, only: %i[index show]
        resources :offers, only: %i[index show]
        resources :bundles, only: %i[index show]
      end

      namespace :catalogue do
        resources :services, only: %i[index]
      end
    end
  end

  resource :api_docs, only: %i[show create]

  resource :admin, only: :show
  namespace :admin do
    resources :jobs, only: :index
    resource :help, only: :show
    resources :help_sections, except: %i[index show]
    resources :help_items, except: %i[index show]
    resource :features, only: [:show]
    resources :tour_feedbacks, except: %i[update destroy]
    post "features/enable_modal"
    post "features/disable_modal"
    resources :lead_sections, except: :show
    resources :leads, except: :show
  end

  # Sidekiq monitoring and split dashboard
  authenticate :user, lambda(&:admin?) do
    require "sidekiq/web"
    mount Sidekiq::Web => "/admin/sidekiq"
  end

  resource :tour_histories, only: :create
  resource :tour_feedbacks, only: :create

  direct :overview_tour_first_service do |params|
    service = Service.where(status: %i[published unverified errored]).order(:name).first
    service_path(service, params)
  end

  get "errors/not_found"
  get "errors/unprocessable"
  get "errors/internal_server_error"
  match "about", to: "pages#about", via: "get", as: :about
  match "target_users", to: "pages#target_users", via: "get", as: :target_users
  match "communities", to: "pages#communities", via: "get", as: :communities
  match "about_projects", to: "pages#about_projects", via: "get", as: :about_projects
  match "landing_page", to: "pages#landing_page", via: "get", as: :landing_page

  if Rails.env.development?
    get "designsystem" => "designsystem#index"
    get "designsystem/:file" => "designsystem#show", :constraints => { file: %r{[^/.]+} }
  end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  include LandingPageHelper
  before_action :load_services,
                :load_root_categories!,
                :load_platforms,
                :load_providers,
                :load_target_users,
                :load_opinion

  layout "clear"

  def index
    @learn_more_section = LeadSection.includes(:leads).find_by(slug: "learn-more")
    @use_cases_section = LeadSection.includes(:leads).find_by(slug: "use-cases")

    # this hack with the research_step is temporary and should be integrated into CMS backend
    # @root_categories_with_logos = @root_categories.with_attached_logo.reject { |c| c.name == "Other" }
    # rubocop:disable Layout/LineLength
    @root_categories_with_logos = [
      {
        name: "Discover Research Outputs",
        logo: "research_step/ico-01.png",
        url: "#{external_search_base_url}/search/all?q=*&fq=unified_categories:(%22Discover%20Research%20Outputs%22)"
      },
      {
        name: "Publish Research Outputs",
        logo: "research_step/ico-02.png",
        url: "#{external_search_base_url}/search/all?q=*&fq=unified_categories:(%22Publish%20Research%20Outputs%22)"
      },
      {
        name: "Access Computing and Storage Services",
        logo: "research_step/ico-03.png",
        url:
          "#{external_search_base_url}/search/all?q=*&fq=unified_categories:(%22Access%20Computing%20and%20Storage%20Resources%22)"
      },
      {
        name: "Process and Analyse",
        logo: "research_step/ico-04.png",
        url: "#{external_search_base_url}/search/all?q=*&fq=unified_categories:(%22Process%20and%20Analyse%22)"
      },
      {
        name: "Access Research Infrastructures",
        logo: "research_step/ico-05.png",
        url:
          "#{external_search_base_url}/search/all?q=*&fq=unified_categories:(%22Access%20Research%20Infrastructures%22)"
      },
      {
        name: "Manage Research Data",
        logo: "research_step/ico-06.png",
        url: "#{external_search_base_url}/search/all?q=*&fq=unified_categories:(%22Manage%20Research%20Data%22)"
      },
      {
        name: "Access Training Material",
        logo: "research_step/ico-07.png",
        url: "#{external_search_base_url}/search/all?q=*&fq=unified_categories:(%22Access%20Training%20Material%22)"
      },
      {
        name: "Find Instruments & Equipment",
        logo: "research_step/ico-09.png",
        url:
          "#{external_search_base_url}/search/all?q=*&fq=unified_categories:(%22Find%20Instruments%20%5C%26%20Equipment%22)"
      }
    ]

    # rubocop:enable Layout/LineLength

    @main_scientific_domains =
      ScientificDomain.with_attached_logo.roots.partition { |sd| sd.name != "Other" }.flatten(1)
    @action = "landing_page"
  end

  def robots
    robots = File.read(Rails.root + "config/robots.#{Rails.application.config.robots}.txt")
    render plain: robots, layout: false, content_type: "text/plain"
  end

  private

  def load_services
    @providers_number = Provider.count
    @services_number = Service.count
    @countries_number = 32
    @services = Service.popular(4)
  end

  def load_platforms
    @home_platforms = Platform.all.uniq.sample(10).map
    @home_platforms_counter = Platform.all.count - @home_platforms.count
  end

  def load_providers
    @home_providers = Provider.active.joins(:services).uniq.sample(5)
    @home_providers_counter = Provider.active.count - @home_providers.count
  end

  def load_target_users
    @home_target_users = TargetUser.all.first(5)
    @home_target_users_counter = TargetUser.all.count - @home_target_users.count
  end

  def load_opinion
    @opinion =
      ServiceOpinion
        .joins(project_item: { offer: :service })
        .where(project_item: { offer: { services: { status: %i[published errored] } } })
        .sample
  end
end

app/views/home/_carousel-card.html.haml
.service-info-box
  %header
    = link_to service.name.truncate(29), service, class: "title"
  %article
    %p
      = presentable_logo(service)
      = truncate(markdown(service.tagline), length: 120, escape: false)
  %footer
    .column-left
      %p
        %small
          = _("Organisation") + ":"
        %br
        = resource_organisation_text(service).truncate(24)
    .column-right
      %p.text-right
        %small
          = _("Dedicated for") + ":"
        %br
        = safe_join(dedicated_for_text(service), ", ").truncate(24)

app/views/home/_communities.html.haml
.standard-list-wrapper{ "data-shepherd-tour-target": "overview_3" }
  .standard-list.two-columns
    = render "home/communities/card",
      key: :related_platforms, records: platforms,
      more_path: communities_path, remaining_count: more_platforms_count,
      cols: 2

  .standard-list
    = render "home/providers/card",
      key: :providers, records: providers,
      more_path: providers_path, remaining_count: more_providers_count

  .standard-list
    = render "home/communities/card",
      key: :dedicated_for, records: target_users,
      more_path: target_users_path, remaining_count: more_target_users_count

app/views/home/_info.html.haml
%a.home-anchor{ href: "#find-eosc", data: { "controller" => "home-page",
                                              "target" => "scrollArrow",
                                              "action" => "scroll@window->home-page#onScroll" } }
  = image_tag("main-link.png")

.contentbox
  %div
    %p.contentbox__title
      = _("Welcome to the EOSC Catalogue and Marketplace")
    %p.contentbox__lead
      -# haml-lint:disable MultilinePipe
      = _("Integrated platform that allows easy access to lots of services for various research domains along" + |
          " with data and integrated data analytics tools. Browse by scientific domain, your current research " + |
          "activity or provider that you know and trust and, if you need help, we are here for you!") |
      -# haml-lint:enable MultilinePipe

    .intro-box-wrapper
      .intro-box
        = _("Find EOSC Services that suit your use case yourself")

        %a{ href: "#{search_service_base_url}/search/all?q=*",
            title: "Discover research products and services all together" }
          %i.fas.fa-arrow-right
          = _("Discover research products and services all together")

        %a{ href: "https://marketplace.eosc-portal.eu/services/",
            title: "Browse through service catalogue" }
          %i.fas.fa-arrow-right
          = _("Browse through service catalogue")

      .intro-box
        =  _("Describe your use case and get support from our experts")
        = link_to projects_path, "data-e2e" => "goToProjectsBtn" do
          %i.fas.fa-arrow-right
          = _("Go to your projects")

  %aside
    = image_tag "gfx_whole_illustation_desktop.png"

app/views/home/_opinions.html.haml
%h2.home-title
  = _("Recent opinions")

- if opinion
  %a#opinion-link.card-title{ href: "#{service_offers_path(opinion.project_item.service)}" }
    = opinion.project_item.service.name
  .row.mt-3
    .col
      .row.pl-4.pr-4.mb-3
        .mr-2= print_rating_stars(opinion.service_rating)
        %span.ml-1.font-weight-bold #{opinion.service_rating}/5
  .card-description
    = opinion.opinion
- else
  = _("There are no reviews available.")

app/views/home/_products.html.haml
#tab-anchor.products.home-tabs.container{ "data-controller" => "home-page", "data-shepherd-tour-target": "overview_2" }
  %ul.tabs
    %li.tab-link.current{ data: { "target" => "home-page.changeTab",
                  "action" => "click->home-page#changeTab", "tab" => "tab-1" },
                  href: "#" } Scientific Domains
    %li.tab-link{ data: { "home-page-target" => "changeTab",
                  "action" => "click->home-page#changeTab", "tab" => "tab-2" },
                  href: "#" } Categories
  #tab-1.tab-content-home.current{ "data-home-page-target" => "tab" }
    .container
      .row
        = render "home/products/cards",
          cards: scientific_domains,
          url: -> (sd) { search_link_router(sd) },
          default_logo: "ico_ra_default.png"

  #tab-2.tab-content-home{ "data-home-page-target" => "tab" }
    .container
      .row
        = render "home/products/cards",
          cards: categories,
          url: -> (category) { category[:url] },
          default_logo: "ico_default.png"

.row.d-flex.justify-content-center.mt-4
  = link_to "Browse all services",
      enable_external_search? ? "#{search_service_base_url}/search/all?q=*": services_path,
      class: "button button--primary",
      "data-shepherd-tour-target": "overview_4"

app/views/home/_services.html.haml
%h2.home-title Popular services

#home-carousel.carousel.slide.home-carousel{ "data-ride" => "carousel" }
  - slices = services.each_slice(3)
  .carousel-inner
    - slices.with_index do |(*slice), i|
      .carousel-item{ class: i&.zero? ? "active" : nil }
        .card-deck
          - slice.each do |service|
            = render "carousel-card", service: service

  %ol.carousel-indicators
    - slices.with_index do |(*_), i|
      %li{ "data-target" => "#home-carousel", "data-slide-to" => i,
             class: i&.zero? ? "active" : nil }

app/views/home/index.html.haml
.landing-header
  %section.heading
    .container
      .row.py-lg-3
        .col-lg-6.col-sm-12.pr-0
          %h1 Polska Platforma Otwartej Nauki
          %p.intro-text
            Wspieramy rozwój polskiej nauki i innowacji, oferując nowoczesne narzędzia
            oraz dostęp do unikalnych danych badawczych.
          = render "services/search",
          categories: @siblings || @root_categories,
          query_params: @query_params || {}
%section.research-activity
  .container
    .row
      .col-md-4.col-sm-12
        = image_tag "eoscpl-pic-01.jpg", alt: "Service name", class: "img-fluid"
      .col-md-8.col-sm-12
        .eoscpl-intro.right-intro
          .eoscpl-intro-title
            Zasoby Polskie
          .eoscpl-intro-desc
            Znajdź treści i narzędzia dedykowane polskiej społeczności badawczej.
            Wybieraj spośród tysięcy zasobów, które ułatwią Ci prowadzenie badań.
            Korzystaj z bogatej oferty informacji oraz wsparcia, które pomogą Ci
            w rozwoju innowacyjnych projektów w kraju i za granicą.
          %a.eoscpl-more-link{ href: "#" }
            Przeglądaj zasoby Polskie
            %i.fas.fa-arrow-right.ml-2

        .eoscpl-intro.right-intro
          .eoscpl-intro-title
            Zasoby Unii Europejskiej
          .eoscpl-intro-desc
            Przeglądaj jedną z największych baz danych naukowych w Europie. Dostęp do milionów publikacji,
            serwisów, oprogramowania i innych narzędzi, które wspierają międzynarodową współpracę
            i rozwój Twoich projektów badawczych.
          %a.eoscpl-more-link{ href: "#" }
            Przeglądaj zasoby europejskie
            %i.fas.fa-arrow-right.ml-2

%section.partners
  .container
    = render_sections("use-cases")

%section.open-science
  .container
    .row
      .col-md-8.col-sm-12
        = render_sections("learn-more")
      .col-md-4.col-sm-12
        = image_tag "eoscpl-pic-02.jpg", alt: "Service name", class: "img-fluid"

%section.programme
  .container
    .row
      .col-md-3.col-sm-12
        %h4
          Polski Węzeł EOSC
      .col-md-6.col-sm-12
        %p
          Polska Platforma Otwartej Nauki jest częścią europejskiej inicjatywy European Open Science Cloud,
          której celem jest rozwój otwartych i dostępnych zasobów badawczych na skalę europejską.
          Jako jeden z krajowych węzłów, Polska wspiera naukowców w dostępie do danych,
          publikacji oraz infrastruktury, która umożliwia prowadzenie zaawansowanych badań i współpracę międzynarodową.
          Krajowe, regionalne i temetyczne węzły EOSC, w tym PPON, stanowią punkty dostępu do Federacji EOSC,
          oferującej własne i zewnętrzne usługi, w tym zarządzanie danymi oraz ich udostępnianie.
      .col-md-3.col-sm-12.d-flex
        %a.programme-link{ href: "#" }
          Przeglądaj wszystkie zasoby
          %i.fa.fa-arrow-right

-# Here should be = render_sections("use-cases") - below is a placeholder
%section.research
  .container
    %h3 Popularne serwisy
    .row
      - @services.each do |service|
        .col-md-3.col-sm-12.d-flex.align-items-stretch
          .popular-services-box.card
            .popular-top
              - if service.logo.attached?
                = image_tag service.logo.variant(resize: "100x80")
              - else
                = image_tag "eosc-img.png", alt: "Service name"
              .badge.access-information.fa-pull-right.badge-right{ class: "style_#{order_type(service)}" }
                %i{ class: "ordertype #{order_type(service)}" }
                -# TODO: refactor dynamic translation
                = t("offers.type.#{order_type(service)}")
            %a.popular-title{ href: service_offers_path(service) }= service.name
            %a.popular-provider{ href: services_path(providers: service.resource_organisation.id) }
              = service.resource_organisation.name
            .popular-description{ data_toggle: "tooltip", title: service.description }
              = service.description.truncate(72)
            - if service.tag_list.present?
              .taglist-holder
                - service.tags.each do |tag|
                  .tag-item
                    = link_to tag, services_path(tag: tag.name)